NUMPY

In [1]:
import numpy as np

In [4]:
matriz = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
type(matriz)

numpy.ndarray

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [7]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.arange(4)

array([0, 1, 2, 3])

In [10]:
np.arange(2, 9, 2) # de 2 até 9, de 2 em 2

array([2, 4, 6, 8])

In [11]:
np.linspace(0, 20, num=5) 

array([ 0.,  5., 10., 15., 20.])

In [12]:
np.ones(5, dtype=np.int64)

array([1, 1, 1, 1, 1])

In [18]:
np.arange?

Docstring:
arange([start,] stop[, step,], dtype=None, *, device=None, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.

Adicionando, Removendo e Classificando Elementos

In [19]:
matriz_x = np.array([2, 1, 5, 3, 7, 4, 6, 8])

In [20]:
np.sort(matriz_x)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])
np.concatenate((x, y))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [25]:
matriz_x.ndim

1

In [26]:
matriz_x.size

8

In [27]:
matriz_x.shape

(8,)